services:
  - type: web
    name: mon-site-django
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn monprojet.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mon-site-db
          property: connectionString
