# Generated by Django 5.2.1 on 2025-06-13 20:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation_message_combinedreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedreservation',
            name='date_debut',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 6, 13))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_debut',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 6, 13))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
